### PR TITLE
Update tm4e upstream, fix issues with symbol matching, and improve completion item list sorting

### LINKED ISSUE #537: TM4E copyright/license headers changed
Dear @Rosemoe,

while looking for showcases for the [Eclipse TM4E](https://github.com/eclipse/tm4e/) project I came across your nice Sora Editor.

Unfortunately I realized that you changed the copyright/license header of all files under https://github.com/Rosemoe/sora-editor/tree/main/language-textmate/src/main/java/org/eclipse/tm4e/languageconfiguration

I'd kindly ask you to revert this change and retain the original copyright/license header.

Thanks a lot in advance!

p.s. You can also consult the EPL Q&A page at https://www.eclipse.org/legal/epl-2.0/faq.php if you have further questions

### PR DESCRIPTION
**Pull request by dingyi222666**
This pull request makes the following changes:

- Update the upstream of tm4e, remove the guava dependency, and follow the requested changes in #537.
- Fix the issue that symbol matching was not enabled by default in the textmate module, and fix the issue that auto-surround did not work properly.
- Fix the errors mentioned in #532 and #420.
- Fix the issue that the completion list was not sorted correctly, and now the completion list should be normal (I apologize for taking so long to fix this low-level error)

### CODE REVIEW

File: language-textmate/src/main/java/org/eclipse/tm4e/core/internal/oniguruma/OnigRegExp.java [hunk 1]
```diff
@@ -42,85 +42,89 @@
...
+                    && lastSearchPosition <= startPosition
+                    && (lastSearchResult0 == null || lastSearchResult0.locationAt(0) >= startPosition)) {
+                return lastSearchResult0;
+            }
+        }
+
+        synchronized (this) {
+            lastSearchString = str;
+            lastSearchPosition = startPosition;
+            lastSearchResult = search(str.bytesUTF8, startPosition, str.bytesCount);
```
Comment (Rosemoe) [inline language-textmate/src/main/java/org/eclipse/tm4e/core/internal/oniguruma/OnigRegExp.java:104]: `search` invocation should not be in synchronized block.

**Review by Rosemoe — CHANGES_REQUESTED** [review]

**Review by Rosemoe — APPROVED** [review]
